# Getting Data

Ocean of datasets on multiple topics, to be organised in future. Use wisely.

1. https://www.kdnuggets.com/2017/12/big-data-free-sources.html
2. https://datasets.opendata.esd.org.uk/
3. https://dataportals.org/search
4. https://opendata.socrata.com/
5. https://registry.opendata.aws/
6. https://www.reddit.com/r/bigquery/wiki/datasets
7. https://opendatamonitor.eu/frontend/web/index.php?r=dashboard%2Findex
8. https://catalog.data.gov/dataset
9. https://ec.europa.eu/eurostat/data/database
10. https://www.re3data.org/
11. https://fairsharing.org/
12. https://datahub.io/
13. https://datahub.io/collections
14. http://archive.ics.uci.edu/ml/datasets.html
15. https://github.com/awesomedata/awesome-public-datasets
16. https://data.europa.eu/euodp/en/data
17. https://stats.oecd.org/
18. https://old.datahub.io/organization/wikimedia
19. https://www.kaggle.com/datasets
20. https://www.quandl.com/search
21. https://www.reddit.com/r/datasets/top/?sort=top&t=all
22. http://academictorrents.com/browse.php?cat=6
23. https://www.data.gov/
24. http://www.tsp-data-portal.org/all-datasets
25. https://www.europeandataportal.eu/data/en/dataset
26. https://dreamtolearn.com/ryan/1001_datasets
27. https://dane.gov.pl/
28. https://github.com/mindsdb/mindsdb

Getting data from multiple sources

1. .CSV table url
2. .xlsx file url
3. .. to be developed.

In [178]:
# Loading data from .csv file url

# Datasource: https://github.com/t-davidson/hate-speech-and-offensive-language

import pandas as pd
import requests
import io
import pandas as pd
import requests
import io

#url = 'https://datahub.io/world-bank/se.prm.nenr/r/data.csv'
url = 'https://raw.githubusercontent.com/t-davidson/hate-speech-and-offensive-language/master/data/labeled_data.csv'

content = requests.get(url).content
df = pd.read_csv(io.StringIO(content.decode('utf-8'))).iloc[:,1:]

print('Shape:', df.shape)
df.head(4)

Shape: (24783, 6)

,count,hate_speech,offensive_language,neither,class,tweet
0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...

In [152]:
# Loading data from .xlsx table file url

# Datasource: https://ndownloader.figshare.com/files/13724144

import pandas as pd
import requests
import io


url = 'https://ndownloader.figshare.com/files/13724144'
df = pd.read_excel(url)

df = df.iloc[:,1:] # drop doubled index column.
print('Shape:', df.shape); df.head(4)

Shape: (40, 21)

,verb,translation,causal_implication,verb_class,verb_bias_category,continuation,p_NP1,p_NP2,p_both,p_other,...,p_NP1_NP1str,p_NP2_NP1str,p_both_NP1str,p_other_NP1str,p_NP1_NP2str,p_NP2_NP2str,p_both_NP2str,p_other_NP2str,pred_p_NP1_NP1str,pred_p_NP1_NP2str
0,anrufen,call,none,unambiguous a-p,NP1,NP1,0.82353,0.08824,0.02941,0.05882,...,0.94118,0.05882,0.0,0.00000,0.66667,0.33333,0.0,0.00000,0.86230,0.74834
1,anschreien,yell at,none,unambiguous a-p,equibiased,NP1,0.32353,0.52941,0.05882,0.08824,...,0.88889,0.05556,0.0,0.05556,0.66667,0.23810,0.0,0.09524,0.80159,0.70392
2,aufregen,agitate,none,unambiguous s-e,NP1,NP2,0.64706,0.23529,0.02941,0.08824,...,0.85714,0.14286,0.0,0.00000,0.61111,0.33333,0.0,0.05556,0.80331,0.65351
3,auslachen,laugh at,NP2,unambiguous a-p,NP2,NP1,0.23529,0.76471,0.00000,0.00000,...,0.61111,0.33333,0.0,0.05556,0.28571,0.66667,0.0,0.04762,0.53058,0.34013